language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: PfbjhwopAVqDIMzhg7CZZ75dTeqKE17cmpZz8L1u4LUSQdlCrH/PalJdcM4GuctWUCzvZYFQmQ5xBpES19wOY9op+c6Y5sgt7Pldyi+zuKbDDvYn3ij/I6kywTCXblfpwTombSX6HNHT3mXxPADWbrLEOlLAxIUwTBTcdjVqhr0nTbQL7GcX9lPqqfk5X22DHJgh+dyyWnUs35M3MNlU9HVWyiwn3pFYFEfArHnn8QX54qefMh83vYCTCy9MBTFqGeWnHwTY0B1Pj9haYESARyFfSRZw2AkjUgOoIBps0pVOzm0yC2IjGRGxK9+IL465m27ew6BQhwJ176jB3lMXzousxth3r1gd+2zY7qLAIsLIECRA/QwEIAQgbhb8r1m4QpCjMfcrLACODZ42IPWWas9fCMT8WYJCeyCXQVF+sSDnIH+dvf5skCSWY2XKu7IK7W9rliIhi7lUytNqNIPj/ohvA1baZQ8bqC0+Mh6lTwQS+BZmj77TVrfgECTDKQ/B1dQO0rU57u1fveMCv0NWsx0wZl7D4dAMHZH44iAjy7fG6ro0rYNWTPl1i1vXttAm/KPhhT0q478gRH3oCPLDKsDA2tv58V0/ojVVKuwjluRlzHh1RfdZSP5KiW5QgelxTPlmiL3zGZaA9QZNArJE6TbccJwo1wZoVbFSO9OJKHc=
